#!/bin/bash

# 1. Busca a URL do .deb mais recente na Release
URL=$(curl -s https://api.github.com/repos/J-Victor-Moraes/configuracaoInicial/releases/latest \
| grep "browser_download_url.*deb" \
| cut -d : -f 2,3 \
| tr -d \" \
| xargs)

# 2. Baixa o arquivo e salva obrigatoriamente como pdv.deb
wget -O pdv.deb "$URL"

# 3. Executa a instalação usando o novo nome
sudo apt install ./pdv.deb -y
